#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace TheTasteReviver.EditorTools
{
    public static class TestLevelAssetGenerator
    {
        private const string Root = "Assets/TheTasteReviver/Generated";
        private const string IngredientsPath = Root + "/Ingredients";
        private const string LevelsPath = Root + "/Levels";
        private const string ScenePath = "Assets/Scenes/TasteRestorer_ReusableTestLevel.unity";
        private const string CurrentTestScenePath = "Assets/Scenes/TasteRestorerTestLevel.unity";
        private const string ExperimentLogScenePath = "Assets/Scenes/ExperimentLog.unity";
        private const string MarkerPath = Root + "/.generated";

        [InitializeOnLoadMethod]
        private static void AutoGenerateOnce()
        {
            EditorApplication.delayCall += () =>
            {
                if (!File.Exists(MarkerPath))
                {
                    GenerateAll();
                }

                EnsureExperimentLogScene();
            };
        }

        [MenuItem("The Taste Reviver/Generate Reusable Test Level")]
        public static void GenerateAll()
        {
            EnsureFolder("Assets", "TheTasteReviver");
            EnsureFolder("Assets/TheTasteReviver", "Generated");
            EnsureFolder(Root, "Ingredients");
            EnsureFolder(Root, "Levels");
            EnsureFolder("Assets", "Scenes");

            List<IngredientData> ingredients = CreateIngredientAssets();
            List<RecipeLevelData> levels = CreateLevelAssets(ingredients);
            CreateScene(ingredients, levels);

            File.WriteAllText(MarkerPath, "Generated by The Taste Reviver test level generator.");
            AssetDatabase.Refresh();
            Debug.Log("Generated The Taste Reviver reusable test level assets and scene.");
        }

        [MenuItem("The Taste Reviver/Bake Placeholder Objects In Current Scene")]
        public static void BakePlaceholderObjectsInCurrentScene()
        {
            if (GameObject.Find("Placeholder Table") != null || GameObject.Find("Mortar Area") != null)
            {
                Debug.LogWarning("Placeholder objects already exist in the current scene. Delete them first if you want to bake a fresh set.");
                return;
            }

            TestLevelInitializer initializer = Object.FindObjectOfType<TestLevelInitializer>();
            if (initializer == null)
            {
                GameObject initializerObject = new GameObject("Taste Restorer Reusable Test Level");
                initializer = initializerObject.AddComponent<TestLevelInitializer>();
            }

            if (initializer.ingredients.Count == 0)
            {
                initializer.ingredients = CreateIngredientAssets();
            }

            if (initializer.levels.Count == 0)
            {
                initializer.levels = CreateLevelAssets(initializer.ingredients);
            }

            initializer.buildOnStart = false;
            initializer.BuildScene();
            EditorUtility.SetDirty(initializer);
            EditorSceneManager.MarkSceneDirty(initializer.gameObject.scene);
            Debug.Log("Baked The Taste Reviver placeholder objects into the current scene.");
        }

        [MenuItem("The Taste Reviver/Clean Placeholder Object Names In Current Scene")]
        public static void CleanPlaceholderObjectNamesInCurrentScene()
        {
            GameObject[] objects = Object.FindObjectsOfType<GameObject>();
            int renamedCount = 0;
            int removedLabelCount = 0;

            foreach (GameObject obj in objects)
            {
                if (obj.name.StartsWith("LABEL_"))
                {
                    Object.DestroyImmediate(obj);
                    removedLabelCount++;
                    continue;
                }

                if (obj.name.StartsWith("ART_SLOT_"))
                {
                    obj.name = CleanArtSlotName(obj.name);
                    EditorUtility.SetDirty(obj);
                    renamedCount++;
                }
            }

            EditorSceneManager.MarkSceneDirty(EditorSceneManager.GetActiveScene());
            Debug.Log("Cleaned placeholder names. Renamed " + renamedCount + " objects and removed " + removedLabelCount + " label objects.");
        }

        [MenuItem("The Taste Reviver/Set Camera To Top Down Workbench View")]
        public static void SetCameraToTopDownWorkbenchView()
        {
            Camera camera = Camera.main;
            if (camera == null)
            {
                camera = new GameObject("Main Camera").AddComponent<Camera>();
                camera.tag = "MainCamera";
            }

            TestLevelInitializer.ConfigureTopDownCamera(camera);
            EditorUtility.SetDirty(camera);
            EditorSceneManager.MarkSceneDirty(camera.gameObject.scene);
            Debug.Log("Set Main Camera to top-down workbench view.");
        }

        [MenuItem("The Taste Reviver/Rebuild UI Layout In Current Scene")]
        public static void RebuildUILayoutInCurrentScene()
        {
            TestLevelInitializer initializer = Object.FindObjectOfType<TestLevelInitializer>();
            if (initializer == null)
            {
                Debug.LogWarning("No TestLevelInitializer found in the current scene.");
                return;
            }

            initializer.RebuildUI();
            initializer.RepairRuntimeReferences();
            initializer.buildOnStart = false;
            EditorUtility.SetDirty(initializer);
            EditorSceneManager.MarkSceneDirty(initializer.gameObject.scene);
            Debug.Log("Rebuilt The Taste Reviver UI layout in the current scene.");
        }

        [MenuItem("The Taste Reviver/Create Experiment Log Scene")]
        public static void EnsureExperimentLogScene()
        {
            EnsureFolder("Assets", "Scenes");

            if (!File.Exists(ExperimentLogScenePath))
            {
                Scene scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Additive);
                GameObject controllerObject = new GameObject("Experiment Log Scene Controller");
                controllerObject.AddComponent<ExperimentLogSceneController>();
                EditorSceneManager.SaveScene(scene, ExperimentLogScenePath);
                EditorSceneManager.CloseScene(scene, true);
            }

            EnsureSceneInBuildSettings(CurrentTestScenePath);
            EnsureSceneInBuildSettings(ExperimentLogScenePath);
            AssetDatabase.Refresh();
        }

        private static string CleanArtSlotName(string name)
        {
            string clean = name.Substring("ART_SLOT_".Length);
            clean = clean.Replace("_Food_Model", " Ingredient");
            clean = clean.Replace("_Tool_Model", "");
            clean = clean.Replace("_Bowl_Model", " Area");
            clean = clean.Replace("_Model", "");
            clean = clean.Replace("_Plate", " Plate");
            clean = clean.Replace('_', ' ');

            if (clean == "Table")
            {
                return "Placeholder Table";
            }

            if (clean == "Mortar Area")
            {
                return "Mortar Area";
            }

            if (clean == "Pestle")
            {
                return "Pestle";
            }

            return clean;
        }

        private static List<IngredientData> CreateIngredientAssets()
        {
            List<IngredientData> source = TestLevelInitializer.CreateRuntimeIngredients();
            List<IngredientData> created = new List<IngredientData>();
            foreach (IngredientData ingredient in source)
            {
                string path = IngredientsPath + "/" + ingredient.ingredientID + ".asset";
                IngredientData asset = AssetDatabase.LoadAssetAtPath<IngredientData>(path);
                if (asset == null)
                {
                    asset = ScriptableObject.CreateInstance<IngredientData>();
                    AssetDatabase.CreateAsset(asset, path);
                }

                EditorUtility.CopySerialized(ingredient, asset);
                asset.name = ingredient.ingredientID;
                EditorUtility.SetDirty(asset);
                created.Add(asset);
            }

            AssetDatabase.SaveAssets();
            return created;
        }

        private static List<RecipeLevelData> CreateLevelAssets(List<IngredientData> ingredients)
        {
            List<RecipeLevelData> source = TestLevelInitializer.CreateRuntimeLevels(ingredients);
            List<RecipeLevelData> created = new List<RecipeLevelData>();
            foreach (RecipeLevelData level in source)
            {
                string path = LevelsPath + "/" + level.levelID + "_" + Sanitize(level.levelName) + ".asset";
                RecipeLevelData asset = AssetDatabase.LoadAssetAtPath<RecipeLevelData>(path);
                if (asset == null)
                {
                    asset = ScriptableObject.CreateInstance<RecipeLevelData>();
                    AssetDatabase.CreateAsset(asset, path);
                }

                EditorUtility.CopySerialized(level, asset);
                asset.name = level.levelID;
                EditorUtility.SetDirty(asset);
                created.Add(asset);
            }

            AssetDatabase.SaveAssets();
            return created;
        }

        private static void CreateScene(List<IngredientData> ingredients, List<RecipeLevelData> levels)
        {
            Scene scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
            GameObject initializerObject = new GameObject("Taste Restorer Reusable Test Level");
            TestLevelInitializer initializer = initializerObject.AddComponent<TestLevelInitializer>();
            initializer.ingredients = ingredients;
            initializer.levels = levels;
            initializer.buildOnStart = false;
            initializer.BuildScene();

            EditorSceneManager.SaveScene(scene, ScenePath);
        }

        private static void EnsureSceneInBuildSettings(string scenePath)
        {
            if (!File.Exists(scenePath))
            {
                return;
            }

            List<EditorBuildSettingsScene> scenes = new List<EditorBuildSettingsScene>(EditorBuildSettings.scenes);
            if (scenes.Exists(x => x.path == scenePath))
            {
                return;
            }

            scenes.Add(new EditorBuildSettingsScene(scenePath, true));
            EditorBuildSettings.scenes = scenes.ToArray();
        }

        private static void EnsureFolder(string parent, string child)
        {
            string path = parent + "/" + child;
            if (!AssetDatabase.IsValidFolder(path))
            {
                AssetDatabase.CreateFolder(parent, child);
            }
        }

        private static string Sanitize(string value)
        {
            foreach (char invalid in Path.GetInvalidFileNameChars())
            {
                value = value.Replace(invalid, '_');
            }

            return value.Replace(' ', '_');
        }
    }
}
#endif
